{
  "formatVersion": "1.1",
  "component": {
    "group": "org.playstrategy",
    "module": "fairystockfish",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.8"
          }
        }
      ],
      "files": [
        {
          "name": "fairystockfish-0.0.18.jar",
          "url": "fairystockfish-0.0.18.jar",
          "size": 24412,
          "sha512": "789de9eb99d584564c1bd2facbeb871e57eedbc3e3183ccfd03d6cfb9de202769a548f2e769e142f5da59460ac14bd87a9fd5abbd2ba27f0cc7f841674f8da50",
          "sha256": "ab54e2c59f310d1ada39cf31952e7011e1d60ced19a8bfdce3901c5ca1734148",
          "sha1": "6a9a6e7eabc28ee1a63272f9a2876e58b23ccde2",
          "md5": "45c01c584b34dbaaabb6a78d82835be1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.8"
          }
        }
      ],
      "files": [
        {
          "name": "fairystockfish-0.0.18.jar",
          "url": "fairystockfish-0.0.18.jar",
          "size": 24412,
          "sha512": "789de9eb99d584564c1bd2facbeb871e57eedbc3e3183ccfd03d6cfb9de202769a548f2e769e142f5da59460ac14bd87a9fd5abbd2ba27f0cc7f841674f8da50",
          "sha256": "ab54e2c59f310d1ada39cf31952e7011e1d60ced19a8bfdce3901c5ca1734148",
          "sha1": "6a9a6e7eabc28ee1a63272f9a2876e58b23ccde2",
          "md5": "45c01c584b34dbaaabb6a78d82835be1"
        }
      ]
    }
  ]
}
