{
  "formatVersion": "1.1",
  "component": {
    "group": "org.playstrategy",
    "module": "fairystockfish",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "fairystockfish-0.0.7.jar",
          "url": "fairystockfish-0.0.7.jar",
          "size": 18147,
          "sha512": "6f4f6327b7bb5a1bfe5bbbc295b4015a25d301fb6ac136fd55abcf1041729a01280ee443fc1145e7207412a8a2fb472e7dfd7c5138edd6cb8a7a762e4810c627",
          "sha256": "4b5ebd4ed3edf46e9cb093ede7ca8b778410a207bce4d4debfe1a9b5d5d41810",
          "sha1": "294cad9042fad885ead775062992785cf3efd838",
          "md5": "2576600ed75a06d5cdb4f0ea36ccbc42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "fairystockfish-0.0.7.jar",
          "url": "fairystockfish-0.0.7.jar",
          "size": 18147,
          "sha512": "6f4f6327b7bb5a1bfe5bbbc295b4015a25d301fb6ac136fd55abcf1041729a01280ee443fc1145e7207412a8a2fb472e7dfd7c5138edd6cb8a7a762e4810c627",
          "sha256": "4b5ebd4ed3edf46e9cb093ede7ca8b778410a207bce4d4debfe1a9b5d5d41810",
          "sha1": "294cad9042fad885ead775062992785cf3efd838",
          "md5": "2576600ed75a06d5cdb4f0ea36ccbc42"
        }
      ]
    }
  ]
}
