{
  "formatVersion": "1.1",
  "component": {
    "group": "org.playstrategy",
    "module": "fairystockfish",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "fairystockfish-0.0.5.jar",
          "url": "fairystockfish-0.0.5.jar",
          "size": 18017,
          "sha512": "d90149d75c64189259c5d9cc5b016f33132f3348ec019cd9eb1745b543108b4ce1a0b8e7fd4b152358095214df9ad4b23963ed09478d815a7a21915f95fa2111",
          "sha256": "42369a87260256545d0a132da4d909e1bedcbafd0e0a9966e7eda9738c1147f0",
          "sha1": "593d779d1311fd560bff560909160b71e1dffd80",
          "md5": "6e1473bbe1b690b46db053ae8cc64fc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bytedeco",
          "module": "javacpp",
          "version": {
            "requires": "1.5.6"
          }
        }
      ],
      "files": [
        {
          "name": "fairystockfish-0.0.5.jar",
          "url": "fairystockfish-0.0.5.jar",
          "size": 18017,
          "sha512": "d90149d75c64189259c5d9cc5b016f33132f3348ec019cd9eb1745b543108b4ce1a0b8e7fd4b152358095214df9ad4b23963ed09478d815a7a21915f95fa2111",
          "sha256": "42369a87260256545d0a132da4d909e1bedcbafd0e0a9966e7eda9738c1147f0",
          "sha1": "593d779d1311fd560bff560909160b71e1dffd80",
          "md5": "6e1473bbe1b690b46db053ae8cc64fc2"
        }
      ]
    }
  ]
}
